name = "SoapySDR"
uuid = "4fa426e6-03fd-45b2-b2dd-25f726820c03"
keywords = ["sdr", "software defined radio", "radio"]
license = "Boost"
desc = "Bindings to the SoapySDR library."
version = "0.2.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
soapysdr_jll = "343a40d9-ed99-5d34-8b56-649aaa4ecee6"

[compat]
Intervals = "1"
Unitful = "1"
julia = "1.6"
soapysdr_jll = "0.8"

[extras]
BinaryBuilder = "12aac903-9f7c-5d81-afc2-d9565ea332ae"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Pkg", "BinaryBuilder", "Libdl"]
