[general]
library_name = "soapysdr"
output_file_path = "../src/libsoapysdr.jl"
extract_c_comment_style = "raw"
wrap_variadic_function = true
print_using_CEnum = false

output_ignorelist = [
    "SOAPY_SDR_API",
    "SOAPY_SDR_LOCAL"
]
