export SOAPY_SDR_TX,
       SOAPY_SDR_RX,
       SOAPY_SDR_END_BURST,
       SOAPY_SDR_HAS_TIME,
       SOAPY_SDR_END_ABRUPT,
       SOAPY_SDR_ONE_PACKET,
       SOAPY_SDR_MORE_FRAGMENTS,
       SOAPY_SDR_WAIT_TRIGGER,
       SOAPY_SDR_TIMEOUT,
       SOAPY_SDR_STREAM_ERROR,
       SOAPY_SDR_CORRUPTION,
       SOAPY_SDR_OVERFLOW,
       SOAPY_SDR_NOT_SUPPORTED,
       SOAPY_SDR_TIME_ERROR,
       SOAPY_SDR_UNDERFLOW

"""SOAPY_SDR_TX SOAPY_SDR_RX"""
@enum Direction Tx = SOAPY_SDR_TX Rx = SOAPY_SDR_RX
